services:
  postgres:
    image: postgres:15-alpine
    container_name: veritix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - veritix_network

  redis:
    image: redis:7-alpine
    container_name: veritix_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - veritix_network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: veritix_backend
    restart: unless-stopped
    ports:
      - '3001:3001'
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - veritix_network

volumes:
  postgres_data:
  redis_data:

networks:
  veritix_network:
    driver: bridge
